# Generated by Django 6.0.6 on 2026-06-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='autor',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
