# Generated by Django 6.0.6 on 2026-07-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_artigo_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='data_publicaçao',
            new_name='data_publicacao',
        ),
    ]
